# Generated by Django 5.2.8 on 2025-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the service image', null=True),
        ),
    ]
