# Generated by Django 5.2.8 on 2025-11-23 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('paypal_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('store_name', models.CharField(max_length=50)),
                ('niche', models.CharField(choices=[('fashion', 'Fashion'), ('pets', 'Pets'), ('beauty', 'Beauty'), ('electronics', 'Electronics'), ('home', 'Home & Kitchen'), ('fitness', 'Fitness')], max_length=30)),
                ('supplier', models.CharField(choices=[('cj', 'CJ Dropshipping'), ('dsers', 'DSers')], max_length=20)),
                ('theme', models.CharField(choices=[('dawn', 'Dawn'), ('refresh', 'Refresh'), ('spotlight', 'Spotlight')], max_length=20)),
                ('color_palette', models.CharField(max_length=100)),
                ('desired_profit_margin', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('markets', models.JSONField(default=list)),
                ('progress', models.CharField(choices=[('paid', 'Payment Received'), ('assigned', 'Staff Assigned'), ('started', 'Store Creation Started'), ('products', 'Products Imported'), ('branding', 'Branding/Theme Configured'), ('review', 'Store Ready for Review'), ('completed', 'Store Delivered')], default='paid', max_length=20)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
